USE testdb

-- 카테고리
CREATE TABLE TB_CATEGORY
(
	IDX INT IDENTITY(1,1),
	CATEGORY_NM VARCHAR(50)

	CONSTRAINT PK_CATEGORY_IDX PRIMARY KEY ( IDX )
)

-- 게시판
CREATE TABLE TB_BOARD
(
	IDX INT IDENTITY(1,1),
	TITLE VARCHAR(200),
	CONTENT VARCHAR(MAX),
	WRITER_NAME VARCHAR(10),
	CREATE_DATE DATETIME,
	MODIFY_DATE DATETIME,
	TAG VARCHAR(500),
	C_IDX INT

	CONSTRAINT PK_BOARD_IDX PRIMARY KEY ( IDX )
	CONSTRAINT FK_BOARD_CATEGORYIDX FOREIGN KEY ( C_IDX )
		REFERENCES TB_CATEGORY ( IDX )
)

-- 댓글
CREATE TABLE TB_REPLY
(
	IDX INT IDENTITY(1,1),
	COMMENT VARCHAR(MAX),
	WRITER_NAME VARCHAR(10),
	CREATE_DATE DATETIME,
	MODIFY_DATE DATETIME,
	B_IDX INT

	CONSTRAINT PK_REPLY_IDX PRIMARY KEY ( IDX )
	CONSTRAINT FK_REPLY_BOARDIDX FOREIGN KEY ( B_IDX )
		REFERENCES TB_BOARD ( IDX )
)

INSERT INTO TB_CATEGORY ( CATEGORY_NM ) VALUES ( '공지사항' )
INSERT INTO TB_CATEGORY ( CATEGORY_NM ) VALUES ( '자유게시판' )
INSERT INTO TB_CATEGORY ( CATEGORY_NM ) VALUES ( 'IT Q&A' )

SELECT * FROM TB_CATEGORY WITH(NOLOCK)

INSERT INTO TB_BOARD ( TITLE, CONTENT, WRITER_NAME, CREATE_DATE, TAG, C_IDX )
			VALUES	 ( '공지사항입니다', '금일 진행 예정이었던 C#특강은 내일로 미뤄졌습니다. 일정에 참고 부탁드립니다.', 'Dexter', GETDATE(), 'Csharp 특강 일정변경', 1 )

INSERT INTO TB_REPLY ( COMMENT, WRITER_NAME, CREATE_DATE, B_IDX )
			VALUES	 ( '앗 ㅠㅠ.. 아쉽네요', 'Jack', GETDATE(), 1 )

INSERT INTO TB_REPLY ( COMMENT, WRITER_NAME, CREATE_DATE, B_IDX )
			VALUES	 ( '진짜 아쉬워요 ㅠㅠㅠ 오늘만을 손꼽아 기다렸는데...', 'Bree', GETDATE(), 1 )

INSERT INTO TB_REPLY ( COMMENT, WRITER_NAME, CREATE_DATE, B_IDX )
			VALUES	 ( '다음주에 뵈어요 ^^', 'Juana', GETDATE(), 1 )

INSERT INTO TB_BOARD ( TITLE, CONTENT, WRITER_NAME, CREATE_DATE, TAG, C_IDX )
			VALUES	 ( '공지사항입니다', '오늘 기습 쪽지시험이 진행 될 예정입니다. 편한 마음으로 출석하세요', 'Dexter', GETDATE(), '테스트 test 기습 공격', 1 )

INSERT INTO TB_REPLY ( COMMENT, WRITER_NAME, CREATE_DATE, B_IDX )
			VALUES	 ( '이건 있을수 없는 일이에요!!', 'Carl', GETDATE(), 2 )

INSERT INTO TB_REPLY ( COMMENT, WRITER_NAME, CREATE_DATE, B_IDX )
			VALUES	 ( '멘붕이다 진짜 ㅋㅋ', 'Jeffrey', GETDATE(), 2 )


SELECT * FROM TB_BOARD