-- RoadbookDB 사용하기
USE RoadbookDB
GO

-- TB_CONTENTS 테이블 만들기
CREATE TABLE TB_CONTENTS
(
	IDX INT IDENTITY(1,1),
	TITLE VARCHAR(20),
	SUMMARY VARCHAR(MAX),
	CREATE_DT DATETIME,
	CREATE_USER_NM VARCHAR(10),
	TAGS VARCHAR(MAX),
	LIKE_CNT INT DEFAULT 0,
	CATEGORY_IDX INT
)
GO