#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadBook.CsharpBasic.Chapter09
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "testdb")]
    public partial class UserDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region 확장성 메서드 정의
        partial void OnCreated();
        partial void InsertTB_USER(TB_USER instance);
        partial void UpdateTB_USER(TB_USER instance);
        partial void DeleteTB_USER(TB_USER instance);
        #endregion

        public UserDataContext() :
                base(global::RoadBook.CsharpBasic.Chapter09.Properties.Settings.Default.testdbConnectionString1, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<TB_USER> TB_USER
        {
            get
            {
                return this.GetTable<TB_USER>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TB_USER")]
    public partial class TB_USER : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _ID;

        private string _NAME;

        private System.Nullable<int> _AGE;

        private string _JOB;

        #region 확장성 메서드 정의
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
        partial void OnAGEChanging(System.Nullable<int> value);
        partial void OnAGEChanged();
        partial void OnJOBChanging(string value);
        partial void OnJOBChanged();
        #endregion

        public TB_USER()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID", DbType = "VarChar(100) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if ((this._ID != value))
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NAME", DbType = "VarChar(100)")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                if ((this._NAME != value))
                {
                    this.OnNAMEChanging(value);
                    this.SendPropertyChanging();
                    this._NAME = value;
                    this.SendPropertyChanged("NAME");
                    this.OnNAMEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AGE", DbType = "Int")]
        public System.Nullable<int> AGE
        {
            get
            {
                return this._AGE;
            }
            set
            {
                if ((this._AGE != value))
                {
                    this.OnAGEChanging(value);
                    this.SendPropertyChanging();
                    this._AGE = value;
                    this.SendPropertyChanged("AGE");
                    this.OnAGEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_JOB", DbType = "VarChar(100)")]
        public string JOB
        {
            get
            {
                return this._JOB;
            }
            set
            {
                if ((this._JOB != value))
                {
                    this.OnJOBChanging(value);
                    this.SendPropertyChanging();
                    this._JOB = value;
                    this.SendPropertyChanged("JOB");
                    this.OnJOBChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
